//gameState.js
export const gameState = {
  currentPhase: 0,
  currentTrial: 0,
  currentVehicle: {type: null, size: null, color: null, x: 0, y: 0, keys: {}},
  score: 0,
  gridWorld: [],
  obstacles: [],
  rewards: [],
  terminator: [],
  startPosition: [],
  inputEnabled: false,
  gameData: {practice: [], phase1: [], phase2: []},
  gameOrder: [],
  learnOrder: [],
  planOrder: [],
  LEARN_POOL: [],
  PLAN_POOL: [],
  vehicleTrialQueueLearn: [],
  vehicleTrialQueuePlan: [],
  mazeId: null,
  optimalRoute: [],
  initialGrid: [],
  RT_L: [],
  RT_P: [],
  totalgametime: 0, 
  starttime: null, 
  endtime: null,
  trialtime: null,
  gameStartTime: null,
}